# Check that environment is working with small dataset
train-small:
	python train.py --data=configs/data_small.json --vocab=configs/vocab.json --training=configs/training.json --model=configs/model.json --output=results/small/

eval-small:
	python evaluate_txt.py --results=results/small/

# TODO fill in makes for training all datasets
# Figure 2: Clean RDKit images
train-small:
	python train.py --data=configs/data_small.json --vocab=configs/vocab.json --training=configs/training.json --model=configs/model.json --output=results/small/

eval-small:
	python evaluate_txt.py --results=results/small/

